version: '3.1'

services:
  mongo_beers:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
    ports:
      - 27017:27017
    networks:
      - op-challenge

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo_beers
    ports:
      - 8081:8081
    networks:
      - op-challenge
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:123@mongo_beers:27017/

networks:
  op-challenge:
    driver: bridge