version: '3.1'
services:
  db-beers:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: beers
    volumes:
      - /srv/docker/postgresql:/var/lib/postgresql
    ports:
      - 5432:5432
    networks:
      - op-challenge

networks:
  op-challenge: